name: "Zeal"
description: "Offline Documentation Browser"

url: "https://zealdocs.org"

permalink: "/blog/:year/:month/:day/:title.html"

# Blog authors
authors:
  trollixx:
    name: "Oleg Shparber"
    github: "trollixx"
  jkozera:
    name: "Jerzy Kozera"
    github: "jkozera"

# Comments
comments:
  disqus: "zealdocs"

# Analytics
analytics:
  google: "UA-436420-7"

# Jekyll Settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed
